# VERSION 0.0.1
# using a tomcat7 image
FROM tomcat:7-jre7
# sign name
MAINTAINER wangzhe "w_hessen@126.com"

#copy the war file into the webapps
ADD /logtest_deploy/logtest.war /usr/local/tomcat/webapps/ 
EXPOSE 22

# port 22


# Tomcat 8080
EXPOSE 8080


