# VERSION 0.0.1
# using a tomcat7 image
FROM baseimage
# sign name
MAINTAINER zju

#copy the war file into the webapps
ADD /newimage /usr/local/tomcat/webapps/


# port 22
EXPOSE 22

# Tomcat 8080
EXPOSE 8080
